### ISSUE TITLE
Problème activation Changement de plaque d'immatriculation

### ISSUE THREAD

**Issue by nans14** [timmaia/fakeplate#1]
Bonjour, @timmaia 

J'ai en ce moment un problème, j'ai mis le SQL ainsi que tout les scripts obligatoire pour mettre en marche le script 

Mais je ne sais pas comment activé le changement de plaque j'ai essayé de me give l'item ect 

Mais cela ne fait rien 

Cordialement Nans14

**Comment by carlosaaraujo** [comment]
@nans14 
Hi, how are you?
I don't understand French very well, would you have a video or a print of the problem?
